# -*- coding: utf-8 -*-
{
  "name": "Modul fulla",
  "description": """OpenERP module loads all installed modules""",
  "version": "0.1.1",
  "author": "Som Energia",
  "category": "Master",
  "depends": [
      'ir_attachment_mongodb',
      'sentry',
      'ws_transactions',
      'res_comarca_canaries',
      'giscedata_switching_cnmc_reports',
      'som_dashboard',
      'giscedata_switching_estimacio',
      'giscedata_municipal_taxes',
      'som_infoenergia',
      'giscedata_cne_circular_2_2005',
      'som_webforms_helpers',
      'som_crawlers',
      'som_extend_facturacio_comer',
      'giscedata_atc_switching_comer',
      'partner_address_tipovia_trg',
      'giscedata_telegestio_comer_switching',
      'report_crm',
      'account_renumber',
      'som_autoreclama',
      'dx_invoice_supplier_renumber',
      'som_energetica',
      'som_empowering',
      'account_account_som',
      'account_analytic_distribution',
      'giscedata_tarifas_pagos_capacidad_20190101',
      'giscedata_tarifas_pagos_capacidad_20210601',
      'l10n_ES_account_balance_report',
      'l10n_ES_cierre_ejercicio',
      'l10n_es_igic',
      'account_import_facturae',
      'empowering_customize',
      'giscedata_cnmc_infde006614_comer',
      'giscedata_escila',
      'giscedata_informes_comptables',
      'giscemisc_informes_scheduler',
      'base_setup',
      'giscedata_dfestius',
      'som_remeses_base',
      'report_aeroo',
      'som_documents_sensibles',
      'uiqmako_helpers',
      'giscedata_facturacio_iva_10',
      'poweremail_campaign',
      'giscedata_facturacio_refund_signed',
      'giscedata_facturacio_som',
      'giscedata_tarifas_cargos_20210601',
      'giscedata_tarifas_cargos_20210916',
      'giscedata_tarifas_cargos_20220101',
      'giscedata_tarifas_cargos_20220301',
      'giscedata_tarifas_peajes_20110401',
      'giscedata_tarifas_peajes_20111001',
      'giscedata_tarifas_peajes_20111223',
      'giscedata_tarifas_peajes_20120101',
      'giscedata_tarifas_peajes_20120401',
      'giscedata_tarifas_peajes_20130801',
      'giscedata_tarifas_peajes_20140201',
      'giscedata_tarifas_peajes_20150101',
      'giscedata_tarifas_peajes_20160101',
      'giscedata_tarifas_peajes_20170101',
      'giscedata_tarifas_peajes_20180101',
      'giscedata_tarifas_peajes_20190101',
      'giscedata_tarifas_peajes_20200101',
      'giscedata_tarifas_peajes_20210916',
      'giscedata_tarifas_peajes_20220101',
      'giscedata_tarifas_peajes_20220301',
      'giscedata_tarifas_peajes_20230101',
      'l10n_ES_aeat_mod347_sql',
      'som_autofactura',
      'giscedata_administracio_publica_miteco',
      'giscedata_facturacio_fraccionaments',
      'giscedata_repercusio_bo_social',
      'l10n_ES_aeat_mod560',
      'som_extend_facturacio_facturae',
      'som_factures_paper',
      'giscedata_facturacio_pool',
      'giscedata_measures_comer',
      'giscedata_sips',
      'som_telemesura',
      'partner_blacklist',
      'som_control_reports',
      'giscedata_atc_facturacio_switching',
      'som_atc',
      'giscedata_facturacio_comer_som',
      'giscedata_facturacio_full_consums_repercussio_ajust_gas',
      'som_account_invoice_pending',
      'giscedata_tipovia_catastro',
      'som_polissa_condicions_generals_m101',
      'som_facturacio_calculada',
      'res_comarca_ib',
      'giscedata_tarifas_pagos_capacidad_20230101',
      'giscedata_tarifas_cargos_20230101',
      'giscedata_polissa_name_auto',
      'l10n_ES_aeat_mod193_from_invoice',
      'giscedata_tarifas_pagos_capacidad_20180101',
      'giscedata_tarifas_peajes_20100701',
      'giscedata_cnmc_ivc',
      'som_l10n_ES_aeat_mod347',
      'spawn_oop',
      'giscedata_facturacio_devolucions',
      'som_informe',
      'giscedata_tarifas_peajes_20210601',
      'giscedata_tarifas_pagos_capacidad_20220101',
      'poweremail_oorq',
      'account_chart_coop_es',
      'ir_access_wizard',
      'gisceorakwlum_client'
    ],
  "init_xml": [],
  "demo_xml": [],
  "update_xml": [],
  "active": False,
  "installable": True
}
